[build]
  # Nenhum comando de build é necessário, pois a Netlify instala as dependências automaticamente
  command = "echo 'Nenhum build necessário'"
  
  # A pasta onde as funções compiladas serão colocadas pela Netlify (padrão)
  functions = ".netlify/functions/"

[functions]
  # Define o empacotador para a função Node.js
  node_bundler = "esbuild"
  # Garante que a pasta node_modules seja incluída no deploy da função
  included_files = ["node_modules/**"]

# Esta é a parte mais importante
[[redirects]]
  # Pega TODAS as requisições que chegam ao site...
  from = "/*"
  # ...e as envia para a nossa função 'api' para serem processadas pelo Express.
  to = "/.netlify/functions/api/:splat"
  # Responde com status 200 (OK), tratando como uma reescrita interna, não um redirecionamento.
  status = 200